/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.text.SimpleDateFormat;
import java.text.ParseException;
/**
 * @author MaximilianoNunesBiscaia,156757
 * @author NayaraRosa,175244
 */
public class Interface_Veterinaria extends javax.swing.JFrame {

    /**
     * Creates new form Interface_Veterinaria
     */
    public Interface_Veterinaria() {
        initComponents();
    }
    
    private Control.Controlador_Veterinaria controle= new Control.Controlador_Veterinaria();;
    private SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CV_Nome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CV_Telefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CV_Gravar = new javax.swing.JButton();
        CV_Endereco = new javax.swing.JTextField();
        CV_Status = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CC_Nome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CC_Endereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CC_Telefone = new javax.swing.JTextField();
        CC_Gravar = new javax.swing.JButton();
        CC_e_mail = new javax.swing.JTextField();
        CC_CEP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CC_Status = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CA_NomeAnimal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CA_Gravar = new javax.swing.JButton();
        CA_Idade = new javax.swing.JTextField();
        Ca_Sexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CA_Especie = new javax.swing.JTextField();
        CA_NomeCliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CA_Status = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        IT_Data_Inicio = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        IT_Gravar = new javax.swing.JButton();
        IT_Data_Fim = new javax.swing.JTextField();
        IT_NomeCliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        IT_NomeAnimal = new javax.swing.JTextField();
        IT_Status = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        MC_Data = new javax.swing.JTextField();
        MC_Historico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MC_Exame = new javax.swing.JTextField();
        MC_Gravar = new javax.swing.JButton();
        MC_NomeCliente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MC_NomeAnimal = new javax.swing.JTextField();
        MC_Status = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        MC_NomeVeterinario = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Pes_1Parametro = new javax.swing.JLabel();
        Pes_2Parametro = new javax.swing.JLabel();
        Pes_combobox = new javax.swing.JComboBox<>();
        Pes_1Parametro_Edit = new javax.swing.JTextField();
        Pes_2Parametro_Edit = new javax.swing.JTextField();
        Pes_res = new javax.swing.JLabel();
        Pes_Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 358));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel5.setText("Nome");

        CV_Nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CV_NomeMouseClicked(evt);
            }
        });

        jLabel6.setText("Endereço");

        CV_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CV_TelefoneActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone");

        CV_Gravar.setText("Gravar");
        CV_Gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CV_GravarMouseClicked(evt);
            }
        });

        CV_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CV_EnderecoActionPerformed(evt);
            }
        });

        CV_Status.setText("Aguardando..");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(CV_Gravar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(39, 39, 39)
                        .addComponent(CV_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CV_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CV_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(692, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(658, Short.MAX_VALUE)
                .addComponent(CV_Status)
                .addGap(281, 281, 281))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(CV_Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CV_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CV_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CV_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(CV_Gravar)
                .addGap(26, 26, 26))
        );

        jTabbedPane4.addTab("Cadastro Veterinario", jPanel3);

        jLabel8.setText("Nome");

        CC_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CC_NomeActionPerformed(evt);
            }
        });

        jLabel9.setText("Endereço");

        CC_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CC_EnderecoActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefone");

        CC_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CC_TelefoneActionPerformed(evt);
            }
        });

        CC_Gravar.setText("Gravar");
        CC_Gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CC_GravarMouseClicked(evt);
            }
        });

        CC_e_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CC_e_mailActionPerformed(evt);
            }
        });

        CC_CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CC_CEPActionPerformed(evt);
            }
        });

        jLabel11.setText("CEP");

        jLabel12.setText("E-mail");

        CC_Status.setText("Aguardando..");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CC_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(CC_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 537, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CC_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CC_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(CC_Gravar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(36, 36, 36)
                                .addComponent(CC_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(CC_Status)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CC_Status)
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CC_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CC_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CC_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(CC_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CC_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 459, Short.MAX_VALUE)
                .addComponent(CC_Gravar)
                .addGap(26, 26, 26))
        );

        jTabbedPane4.addTab("Cadastro Cliente", jPanel4);

        jLabel1.setText("Nome Animal");

        jLabel2.setText("Idade");

        jLabel3.setText("Sexo");

        CA_Gravar.setText("Gravar");
        CA_Gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CA_GravarMouseClicked(evt);
            }
        });

        CA_Idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CA_IdadeActionPerformed(evt);
            }
        });

        Ca_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        Ca_Sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ca_SexoActionPerformed(evt);
            }
        });

        jLabel4.setText("Especie");

        jLabel19.setText("Nome Cliente");

        CA_Status.setText("Aguardando...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Ca_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CA_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CA_NomeCliente)
                                .addComponent(CA_NomeAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(CA_Especie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(129, 129, 129))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(CA_Gravar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(CA_Status)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CA_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CA_NomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CA_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(CA_Especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Ca_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(CA_Status)
                .addGap(18, 18, 18)
                .addComponent(CA_Gravar)
                .addGap(31, 31, 31))
        );

        jTabbedPane4.addTab("Cadastro animal", jPanel2);

        jLabel16.setText("Data início");

        IT_Data_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT_Data_InicioActionPerformed(evt);
            }
        });

        jLabel17.setText("Data fim");

        IT_Gravar.setText("Gravar tratamento");
        IT_Gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IT_GravarMouseClicked(evt);
            }
        });
        IT_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT_GravarActionPerformed(evt);
            }
        });

        IT_Data_Fim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IT_Data_FimActionPerformed(evt);
            }
        });

        jLabel20.setText("Nome Cliente");

        jLabel21.setText("Nome Animal");

        IT_Status.setText("Aguardando...");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(IT_Gravar))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel21))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(IT_NomeCliente)
                                        .addComponent(IT_NomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IT_Data_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IT_Data_Fim, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(IT_Status)))
                .addContainerGap(625, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IT_Status)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IT_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IT_NomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IT_Data_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IT_Data_Fim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(25, 25, 25)
                .addComponent(IT_Gravar)
                .addGap(22, 22, 22))
        );

        jTabbedPane4.addTab("Iniciar Tratamento", jPanel6);

        MC_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_DataActionPerformed(evt);
            }
        });

        MC_Historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_HistoricoActionPerformed(evt);
            }
        });

        jLabel13.setText("Historico");

        jLabel14.setText("Data");

        jLabel15.setText("Exame");

        MC_Exame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_ExameActionPerformed(evt);
            }
        });

        MC_Gravar.setText("Gravar consulta");
        MC_Gravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MC_GravarMouseClicked(evt);
            }
        });
        MC_Gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_GravarActionPerformed(evt);
            }
        });

        jLabel22.setText("Nome Cliente");

        jLabel23.setText("Nome Animal");

        MC_Status.setText("Aguardando...");

        jLabel24.setText("Nome Veterinario");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(MC_NomeCliente)
                                    .addComponent(MC_NomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MC_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(MC_Historico)
                                        .addComponent(MC_Exame, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(MC_NomeVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(58, 58, 58)
                        .addComponent(MC_Gravar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(MC_Status)))
                .addContainerGap(465, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MC_Status)
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MC_NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MC_NomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MC_NomeVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(MC_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MC_Gravar))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MC_Historico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(MC_Exame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPane4.addTab("Marcar Consulta", jPanel5);

        jButton1.setText("Gerar Relatório");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        jTabbedPane4.addTab("Relatório", jPanel7);

        Pes_1Parametro.setText("Nome: ");

        Pes_2Parametro.setText("Nome_Animal: ");

        Pes_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veterinario", "Cliente", "Consulta", "Animal" }));

        Pes_res.setText("Resultado da pesquisa:");

        Pes_Pesquisar.setText("Pesquisar");
        Pes_Pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pes_PesquisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pes_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pes_1Parametro)
                            .addComponent(Pes_2Parametro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pes_Pesquisar)
                            .addComponent(Pes_1Parametro_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pes_2Parametro_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94)
                .addComponent(Pes_res, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pes_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pes_1Parametro)
                            .addComponent(Pes_1Parametro_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pes_2Parametro_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pes_2Parametro))
                        .addGap(18, 18, 18)
                        .addComponent(Pes_Pesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Pes_res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(520, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Pesquisa", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CA_IdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CA_IdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CA_IdadeActionPerformed

    private void CV_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CV_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CV_TelefoneActionPerformed

    private void CV_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CV_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CV_EnderecoActionPerformed

    private void CC_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CC_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CC_EnderecoActionPerformed

    private void CC_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CC_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CC_TelefoneActionPerformed

    private void CC_e_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CC_e_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CC_e_mailActionPerformed

    private void CC_CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CC_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CC_CEPActionPerformed

    private void CC_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CC_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CC_NomeActionPerformed

    private void MC_ExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_ExameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MC_ExameActionPerformed

    private void MC_HistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_HistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MC_HistoricoActionPerformed

    private void MC_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MC_DataActionPerformed

    private void IT_Data_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT_Data_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IT_Data_InicioActionPerformed

    private void IT_Data_FimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT_Data_FimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IT_Data_FimActionPerformed

    private void IT_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IT_GravarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IT_GravarActionPerformed

    private void MC_GravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_GravarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MC_GravarActionPerformed

    private void Ca_SexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ca_SexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ca_SexoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void CV_NomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CV_NomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CV_NomeMouseClicked

    private void CV_GravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CV_GravarMouseClicked
        
        controle.writeVeterinario(CV_Nome.getText(), CV_Endereco.getText(), CV_Telefone.getText());
        CV_Status.setText(CV_Nome.getText() + " cadastrado!");
        // TODO add your handling code here:
    }//GEN-LAST:event_CV_GravarMouseClicked

    private void CC_GravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CC_GravarMouseClicked
        
        controle.writeCliente(CC_Nome.getText(),CC_Endereco.getText(),CC_Telefone.getText(),Integer.parseInt(CC_CEP.getText()),CC_e_mail.getText());
        CC_Status.setText(CC_Nome.getText() + " cadastrado!");
        // TODO add your handling code here:
    }//GEN-LAST:event_CC_GravarMouseClicked

    private void Pes_PesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pes_PesquisarMouseClicked
            String[] resultado,resultadoaux;
            String[][] animais;
            String aux;
        switch(Pes_combobox.getSelectedIndex()){
            
            case 0:
                resultado = (controle.consultaVeterinario(Pes_1Parametro_Edit.getText()));
                
                Pes_res.setText("<html>"+"Resultado da pesquisa: "+"<br />"+
                        " Nome: "+resultado[0]+"<br />"+
                        " Telefone: "+resultado[1]+"<br />"+
                        " Email: "+resultado[2]+"</html>");
                
                break;
            case 1:
                resultado = controle.consultaCliente(Pes_1Parametro_Edit.getText());
                //animais = controle.retornarAnimal(Pes_1Parametro_Edit.getText());
                int i = 0,n = 0;
                
                Pes_res.setText("<html>"+"Resultado da pesquisa: "+"<br />"+
                        " Nome: "+resultado[0]+"<br />"+
                        " Telefone: "+resultado[1]+"<br />"+
                        " Email: "+resultado[2]+"<br />"+
                        " CEP: "+resultado[3]+"<br />"+
                        " E-mail: "+resultado[4]+"</html>");
                /*for(;i<animais.length;i++){
                    aux = (aux+"<br />"+
                            animais[i][0]+" "+animais[i][3]);
                }
                aux = (Pes_res.getText()+"</html>");
                Pes_res.setText(Pes_res.getText()+"</html>");*/
                break;
            case 3:
                resultado = controle.consultaAnimal(Pes_1Parametro_Edit.getText(),Pes_2Parametro_Edit.getText());
                
                Pes_res.setText("<html>"+"Resultado da pesquisa: "+"<br />"+
                        " Nome: "+resultado[0]+"<br />"+
                        " Idade: "+resultado[1]+"<br />"+
                        " Sexo: "+resultado[2]+"<br />"+
                        " Especie: "+resultado[3]+"</html>");
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Pes_PesquisarMouseClicked

    private void CA_GravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CA_GravarMouseClicked
            
            String [] resultado;
            resultado = controle.consultaCliente(CA_NomeCliente.getText());
            if(resultado[0] == null){
                CA_Status.setText(" Cliente não encontrado!");
    }else{
            controle.writeAnimal(CA_NomeCliente.getText(), CA_NomeAnimal.getText(), CA_Idade.getText(),(Ca_Sexo.getSelectedIndex()==0 ? "Masculino" : "Feminino"),CA_Especie.getText());
            CA_Status.setText(CA_NomeAnimal.getText() + " cadastrado!");
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_CA_GravarMouseClicked

    private void IT_GravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IT_GravarMouseClicked
       
        
        
    String [] resultado, resultado1;
            resultado = controle.consultaCliente(IT_NomeCliente.getText());
            resultado1 = controle.consultaAnimal(IT_NomeCliente.getText(),IT_NomeAnimal.getText());
    if((resultado[0] == null)||(resultado1[0]==null)){
                IT_Status.setText(" Cliente/Animal não encontrado!");
    }else{
                 try{
           
                controle.writeTratamento(IT_NomeCliente.getText(),IT_NomeAnimal.getText(), formato.parse(IT_Data_Inicio.getText()), formato.parse(IT_Data_Fim.getText()));
                IT_Status.setText("Tratamento de "+IT_NomeAnimal.getText() + " cadastrado!");
                 }catch(ParseException e){
                     IT_Status.setText("Data inicio ou Data fim inseridas fora do formato DD/MM/AAAA (DIA = DD, MÊS = MM e ANO = AAAA)");
                 }
    }
// TODO add your handling code here:
    }//GEN-LAST:event_IT_GravarMouseClicked

    private void MC_GravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MC_GravarMouseClicked
        
        String [] resultado, resultado1,resultado2;
        
            resultado = controle.consultaCliente(MC_NomeCliente.getText());
            resultado1 = controle.consultaAnimal(MC_NomeCliente.getText(),MC_NomeAnimal.getText());
            resultado2 = controle.consultaVeterinario(MC_NomeVeterinario.getText());
    if((resultado[0] == null)||(resultado1[0]==null)||(resultado2[0]==null)){
                MC_Status.setText(" Cliente/Animal/Veterinario não encontrado!");
    }else{
                 try{
                        
                        if(controle.consultaTratamento(MC_NomeCliente.getText(),MC_NomeAnimal.getText(), formato.parse(MC_Data.getText()))){
                            if("".equals(MC_Exame.getText())){
                                controle.writeConsulta(MC_NomeCliente.getText(),MC_NomeAnimal.getText(), (MC_Data.getText()),MC_Historico.getText(),MC_NomeVeterinario.getText());
                            }else{
                                controle.writeConsulta(MC_NomeCliente.getText(),MC_NomeAnimal.getText(), (MC_Data.getText()),MC_Historico.getText(),MC_NomeVeterinario.getText(),MC_Exame.getText()); 
                            }

                            MC_Status.setText("Consulta de "+MC_NomeAnimal.getText() + " cadastrada!");
                        }else{
                            MC_Status.setText("Não há data de tratamento iniciada para a data de consulta inserida.");
                        }
                 }catch(ParseException e){
                        MC_Status.setText("Data inserida fora do formato DD/MM/AAAA (DIA = DD, MÊS = MM e ANO = AAAA)");
                 }
    }
        
// TODO add your handling code here:
    }//GEN-LAST:event_MC_GravarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int x,y;
        String [][] dados= controle.tabelaVeterinario();
        
        
        for(x=0,y=0;dados[y][x]!= null;y++)  
            for(x=0;x<3;x++)
                 jTable1.setValueAt(dados[y][x], y, x);
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_Veterinaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_Veterinaria().setVisible(true);
         
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CA_Especie;
    private javax.swing.JButton CA_Gravar;
    private javax.swing.JTextField CA_Idade;
    private javax.swing.JTextField CA_NomeAnimal;
    private javax.swing.JTextField CA_NomeCliente;
    private javax.swing.JLabel CA_Status;
    private javax.swing.JTextField CC_CEP;
    private javax.swing.JTextField CC_Endereco;
    private javax.swing.JButton CC_Gravar;
    private javax.swing.JTextField CC_Nome;
    private javax.swing.JLabel CC_Status;
    private javax.swing.JTextField CC_Telefone;
    private javax.swing.JTextField CC_e_mail;
    private javax.swing.JTextField CV_Endereco;
    private javax.swing.JButton CV_Gravar;
    private javax.swing.JTextField CV_Nome;
    private javax.swing.JLabel CV_Status;
    private javax.swing.JTextField CV_Telefone;
    private javax.swing.JComboBox<String> Ca_Sexo;
    private javax.swing.JTextField IT_Data_Fim;
    private javax.swing.JTextField IT_Data_Inicio;
    private javax.swing.JButton IT_Gravar;
    private javax.swing.JTextField IT_NomeAnimal;
    private javax.swing.JTextField IT_NomeCliente;
    private javax.swing.JLabel IT_Status;
    private javax.swing.JTextField MC_Data;
    private javax.swing.JTextField MC_Exame;
    private javax.swing.JButton MC_Gravar;
    private javax.swing.JTextField MC_Historico;
    private javax.swing.JTextField MC_NomeAnimal;
    private javax.swing.JTextField MC_NomeCliente;
    private javax.swing.JTextField MC_NomeVeterinario;
    private javax.swing.JLabel MC_Status;
    private javax.swing.JLabel Pes_1Parametro;
    private javax.swing.JTextField Pes_1Parametro_Edit;
    private javax.swing.JLabel Pes_2Parametro;
    private javax.swing.JTextField Pes_2Parametro_Edit;
    private javax.swing.JButton Pes_Pesquisar;
    private javax.swing.JComboBox<String> Pes_combobox;
    private javax.swing.JLabel Pes_res;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
